//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    using WebAPI.Interfaces;

    public partial class Addresses
    {
        public int address_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> street_number { get; set; }
        public string street_name { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
    
        public virtual Customers customer { get; set; }
    }
}
